version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biologics-platform-app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/biologics_platform
      - DATABASE_NAME=biologics_platform
      - RESEND_API_KEY=re_J3RrdafA_81u7vZKyiDd3LsbsqfziC8DX
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: biologics-platform-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
