from fpdf import FPDF
from datetime import datetime
import os

class BioDiscoveryReport(FPDF):
    def header(self):
        # Arial bold 15
        self.set_font('Arial', 'B', 20)
        # Colors: Deep Blue
        self.set_text_color(26, 35, 126)
        # Title
        self.cell(0, 10, 'GenQuantis Discovery Platform', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100)
        self.cell(0, 10, 'AI Lead Optimization & Molecular Analysis Report', 0, 1, 'C')
        # Line break
        self.ln(5)
        # Blue horizontal line
        self.set_draw_color(26, 35, 126)
        self.set_line_width(1)
        self.line(10, 32, 200, 32)
        self.ln(10)
        
    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')
        # Date
        self.cell(0, 10, f'Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'R')

def generate_pdf_report(target_name: str, summary_data: dict, molecules: list, user=None):
    """
    Generates a PDF summary for scientific researchers.
    summary_data = { "pIC50_avg": 7.2, "top_hits": 5, "total_screened": 1000000 }
    """
    pdf = BioDiscoveryReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Section Header
    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' LEAD OPTIMIZATION ANALYSIS REPORT', 0, 1, 'L', fill=True)
    pdf.ln(3)
    
    # User Metadata Banner
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(100)
    user_name = user.full_name or user.email if user else "System Administrator"
    gen_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    pdf.cell(0, 8, f"Report Generated by {user_name} on {gen_time}", 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # Metadata
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Target Name:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(target_name), 0, 1)
    
    # Discovery Summary Section
    pdf.ln(5)
    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Optimization Metrics Summary', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.ln(2)
    
    fill = False
    for k, v in summary_data.items():
        pdf.set_fill_color(245, 245, 245)
        label = k.replace("_", " ").title()
        pdf.cell(60, 8, label, 1, 0, 'L', fill=fill)
        pdf.cell(130, 8, str(v), 1, 1, 'L', fill=fill)
        fill = not fill
    pdf.ln(10)
    
    # Top Hit Molecules
    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Optimized Lead Candidates (Top 10)', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    
    # Table Header
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(20, 10, 'Rank', 1, 0, 'C', fill=True)
    pdf.cell(130, 10, 'SMILES Signature', 1, 0, 'C', fill=True)
    pdf.cell(40, 10, 'Affinity (pIC50)', 1, 1, 'C', fill=True)
    
    # Table Body
    pdf.set_font('Arial', '', 9)
    for i, mol in enumerate(molecules[:10]):
        pdf.cell(20, 8, str(i + 1), 1, 0, 'C')
        pdf.cell(130, 8, str(mol.get('smiles', ''))[:60] + ("..." if len(str(mol.get('smiles', ''))) > 60 else ""), 1, 0, 'L')
        pdf.cell(40, 8, f"{float(mol.get('affinity', 0)):.2f}", 1, 1, 'C')
    pdf.ln(10)

    # Disclaimer
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 6, "Platform Disclaimer: This report is generated by GenQuantis Lead Optimization AI. Structural and bioactivity data is retrieved and optimized using machine learning algorithms. Experimental validation is required for target tractability.")

    # Save to buffer or file
    filename = f"report_{target_name}_{os.urandom(2).hex()}.pdf"
    output_path = f"/tmp/{filename}" if os.name != 'nt' else f"./temp_uploads/{filename}"
    
    if not os.path.exists("./temp_uploads"):
        os.makedirs("./temp_uploads")
        
    pdf.output(output_path)
    return output_path
